// LO QUE SOSTIENE LA NUMERACIÓN CORRELATIVA DE RECIBOS (dueño, 02/10/2026), leído del código: no hay base en el
// test. Cada caso existe porque su contrario es un defecto concreto: un hueco en la serie, un número que cambia
// después de impreso, un papel que sale sin número o con uno inventado, el portal tocado.
import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const RAIZ = new URL('../../../', import.meta.url).pathname
const sinComentarios = (s: string) => s.replace(/\/\*[\s\S]*?\*\//g, '').replace(/^\s*(--|\/\/).*$/gm, '')
const leer = (r: string) => sinComentarios(readFileSync(`${RAIZ}${r}`, 'utf8'))
const MIG = 'supabase/migrations/'
const SQL = leer(`${MIG}20261002T1200_recibos_numeracion_correlativa.sql`)

/** El cuerpo de la ÚLTIMA definición de una función en el texto (hasta el `end $$`). */
function cuerpo(sql: string, fn: string): string {
  const i = sql.lastIndexOf(`create or replace function public.${fn}(`)
  assert.ok(i >= 0, `no está ${fn}`)
  return sql.slice(i, sql.indexOf('end $$', i))
}
/** La lista de parámetros tal como se declaró, sin espacios. */
const firma = (sql: string, fn: string): string => {
  const m = /\(([\s\S]*?)\)\s*returns/.exec(cuerpo(sql, fn))
  assert.ok(m, `no leo los parámetros de ${fn}`)
  return m[1].replace(/\s+/g, '')
}

test('la serie avanza con update … returning bajo lock, nunca con una sequence (que deja huecos en cada rollback)', () => {
  const tomar = cuerpo(SQL, 'tomar_numero_de_recibo')
  assert.match(tomar, /update public\.recibo_serie set ultimo = ultimo \+ 1 where serie = p_serie returning ultimo into v_numero/)
  assert.match(tomar, /raise exception 'la serie de recibos/)
  assert.doesNotMatch(SQL, /nextval|create sequence|generated always as identity|generated by default/i)
})

test('nadie toma números sueltos por la API: sin execute para authenticated ni anon', () => {
  assert.match(SQL, /revoke all on function public\.tomar_numero_de_recibo\(text\) from public, anon, authenticated;/)
  assert.doesNotMatch(SQL, /grant execute on function public\.tomar_numero_de_recibo[^;]*\b(authenticated|anon|public)\b/)
  assert.match(SQL, /revoke all on public\.recibo_serie from anon, public, authenticated;/)
  assert.doesNotMatch(SQL, /grant (insert|update|delete|all)[^;]*recibo_serie/i)
})

test('dos series: RP para todos los pagos y RC que sigue al mayor número entero ya entregado al cliente', () => {
  assert.match(SQL, /values \('RP', '[^']+', 0\)\s*on conflict \(serie\) do nothing/)
  assert.match(SQL, /coalesce\(max\(btrim\(numero\)::integer\), 0\)\s*from public\.recibo_cliente\s*where btrim\(numero\) ~ '\^\[0-9\]\{1,9\}\$'/)
  // Correrla otra vez no BAJA una serie que ya avanzó (repetiría números entregados).
  assert.match(SQL, /do update set ultimo = greatest\(public\.recibo_serie\.ultimo, excluded\.ultimo\)/)
})

test('el código no trunca: seis dígitos son relleno (lpad cortaba el 1.234.567 en «123456»)', () => {
  const c = cuerpo(SQL, 'codigo_de_recibo')
  assert.match(c, /length\(p_numero::text\) >= 6 then p_numero::text/)
  assert.match(c, /lpad\(p_numero::text, 6, '0'\)/)
  assert.match(SQL, /function public\.codigo_de_recibo\(p_serie text, p_numero integer\) returns text\s*language plpgsql immutable strict/)
})

for (const [fn, tabla, original] of [
  ['registrar_recibo_liquidacion', 'recibo_liquidacion', '20260922T2600_recibo_liquidacion.sql'],
  ['firmar_recibo_gasto_manual', 'efectivo_recibo_firma', '20261001T0900_efectivo_recibo_firmado.sql'],
] as const) {
  test(`${fn}: toma RP después de validar y en la misma transacción del insert, con la misma firma de antes`, () => {
    const c = cuerpo(SQL, fn)
    const toma = c.indexOf("v_numero := public.tomar_numero_de_recibo('RP');")
    assert.ok(toma > 0, 'no toma número de la serie RP')
    // Un recibo rechazado no consume número: ninguna validación después de tomarlo.
    assert.ok(c.lastIndexOf('raise exception') < toma, 'hay una validación después de tomar el número')
    assert.ok(c.indexOf(`insert into ${tabla === 'recibo_liquidacion' ? 'recibo_liquidacion' : 'public.efectivo_recibo_firma'}`) > toma)
    assert.match(c, /serie_numero, codigo\)/)
    assert.match(c, /v_numero, public\.codigo_de_recibo\('RP', v_numero\)\)/)
    // MISMOS PARÁMETROS: con otros, `create or replace` crearía una SOBRECARGA y la vieja —sin número— seguiría viva.
    assert.equal(firma(SQL, fn), firma(leer(`${MIG}${original}`), fn))
  })

  test(`${tabla}: número y código obligatorios, únicos y coherentes entre sí`, () => {
    assert.match(SQL, new RegExp(`alter table public\\.${tabla} alter column serie_numero set not null`))
    assert.match(SQL, new RegExp(`alter table public\\.${tabla} alter column codigo set not null`))
    assert.match(SQL, new RegExp(`create unique index if not exists ${tabla}_serie_numero_key on public\\.${tabla} \\(serie_numero\\)`))
    assert.match(SQL, new RegExp(`create unique index if not exists ${tabla}_codigo_key on public\\.${tabla} \\(codigo\\)`))
    assert.match(SQL, new RegExp(`${tabla}_codigo_de_su_numero\\s*check \\(codigo = public\\.codigo_de_recibo\\('RP', serie_numero\\)\\)`))
  })
}

test('el número impreso no cambia: trigger en la quincena, y el de efectivo vuelve a quedar prendido', () => {
  const t = cuerpo(SQL, '_recibo_numero_inmutable')
  assert.match(t, /old\.serie_numero is not null/)
  assert.match(t, /new\.serie_numero is distinct from old\.serie_numero or new\.codigo is distinct from old\.codigo/)
  assert.match(SQL, /create trigger recibo_liquidacion_numero_inmutable before update on public\.recibo_liquidacion/)
  const apaga = SQL.indexOf('disable trigger efectivo_recibo_firma_inmutable')
  const prende = SQL.indexOf('enable trigger efectivo_recibo_firma_inmutable')
  assert.ok(apaga > 0 && prende > apaga, 'el trigger de efectivo se apaga para el backfill y se vuelve a prender')
  assert.equal(SQL.split('disable trigger').length, 2, 'se apaga una sola vez')
})

test('los ya emitidos se numeran en el orden en que se emitieron, sólo los que no tienen número', () => {
  assert.match(SQL, /alter column codigo drop expression if exists/)
  assert.match(SQL, /row_number\(\) over \(order by numero, id\)[\s\S]{0,80}where serie_numero is null/)
  assert.match(SQL, /update public\.recibo_serie set ultimo = ultimo \+ v_n where serie = 'RP'/)
})

test('EL PORTAL NO SE TOCA: la migración no escribe recibo_cliente y ningún cambio entra en src/app/portal', () => {
  assert.doesNotMatch(SQL, /(update|alter table|delete from|insert into)\s+public\.recibo_cliente/i)
  for (const a of ['src/app/portal/recibos.ts', 'src/app/portal/recibo/[id]/route.ts']) {
    assert.doesNotMatch(leer(a), /codigoDeRecibo|RC-/)
  }
})

test('CABLEADO: lo que se imprime lleva el número; la vista previa no inventa uno', () => {
  const hoja = leer('src/features/administracion/components/liquidacion/cuadro/HojaDelRecibo.tsx')
  assert.match(hoja, /rotuloDelNumero\(codigo\)/)
  assert.match(leer('src/features/administracion/components/liquidacion/cuadro/HojasDeRecibosA4.tsx'), /rotuloDelNumero\(r\.codigo\)/)
  assert.match(leer('src/features/administracion/services/recibosLotePdf.ts'), /rotuloDelNumero\(r\.codigo\)/)
  assert.match(leer('src/features/efectivo/services/reciboPdf.ts'), /rotuloDelNumero\(firma\.codigo\)/)
  // La ruta del PDF lee el código de lo guardado.
  assert.match(leer('src/app/(main)/administracion/personas/recibos-lote/route.ts'), /select\('id, codigo,/)
  const previa = leer('src/features/administracion/components/liquidacion/cuadro/VistaPreviaDeRecibos.tsx')
  // `.map(aLaHoja)` le pasaría el ÍNDICE como código: el recibo 3 de la vista previa diría «Recibo N° 2».
  assert.doesNotMatch(previa, /\.map\(aLaHoja\)/)
  assert.match(previa, /aLaHoja\(g\.recibo, g\.codigo\)/)
  // El individual imprime con el número ya dibujado: redibuja sincrónico antes de copiar el HTML.
  const armar = leer('src/features/administracion/components/liquidacion/cuadro/ArmarRecibo.tsx')
  assert.ok(armar.indexOf('flushSync(() => setCodigo(r.codigo))') > 0)
  assert.ok(armar.indexOf('flushSync(() => setCodigo(r.codigo))') < armar.indexOf('const salio = imprimir()'))
  assert.match(armar, /codigo=\{codigo\}/)
  assert.match(leer('src/features/administracion/components/RecibosEmitidos.tsx'), /codigo=\{r\.codigo\}/)
})

test('CABLEADO: guardar devuelve el número leído de la fila, y el mismo papel conserva el suyo', () => {
  const acc = leer('src/features/administracion/services/recibosEmitidosActions.ts')
  assert.match(acc, /from\('recibo_liquidacion'\)\.select\('id, emitido_en, codigo'\)/)
  assert.match(acc, /ok: true, id: ya\.id, codigo: ya\.codigo, yaEstaba: true/)
})

test('el script del recibo de cobro no tiene el número escrito: lo toma de RC sólo con --aplicar', () => {
  const s = leer('orquestador/scripts/recibo-cliente-armar.mjs')
  assert.doesNotMatch(s, /numero:\s*'\d+'/)
  assert.match(s, /tomar_numero_de_recibo\('RC'\)/)
  const previa = s.slice(s.indexOf("if (!argv.includes('--aplicar'))"), s.indexOf('const datos = await withTx'))
  assert.doesNotMatch(previa, /tomar_numero_de_recibo|writeFileSync/, 'la vista previa no consume número ni escribe el JSON')
  // El JSON se escribe DENTRO de la transacción: si falla, el número vuelve a la serie.
  const tx = s.slice(s.indexOf('await withTx'))
  assert.ok(tx.indexOf('tomar_numero_de_recibo') < tx.indexOf('writeFileSync'))
})
