-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- DOS DECISIONES EMPATAN Y GANA CUALQUIERA
-- ═══════════════════════════════════════════════════════════════════════════════════════════════
--
-- ── EL DEFECTO, MEDIDO ────────────────────────────────────────────────────────────────────────
--
-- `decidido_en` tenía `default now()`, y `now()` en Postgres NO es la hora actual: es la hora de
-- INICIO DE LA TRANSACCIÓN. Dos decisiones guardadas en la misma transacción quedan con el mismo
-- timestamp al microsegundo, y `order by decidido_en desc limit 1` devuelve **cualquiera de las
-- dos**: el orden lo termina decidiendo el plan de ejecución, no la cronología.
--
-- Lo atrapó el test «la tabla es append-only: gana la última»: se guardó T1018, después
-- NO_HAY_ANALISIS, y la lectura devolvió T1018. O sea: alguien cambia de opinión, el sistema le
-- dice que sí, y sigue cotizando con la decisión vieja sin avisar.
--
-- No es un artefacto del test. Es peor en producción, donde el empate no se ve: dos correcciones
-- seguidas dentro del mismo request caen en la misma transacción, y la que gana es la que quiera el
-- planificador. Es exactamente el defecto que `seleccion.mjs` ya tiene documentado para el catálogo
-- —«el desempate por código es lo que hace esto reproducible»— aplicado al orden del tiempo.
--
-- ── LA CORRECCIÓN: UN ORDEN QUE NO PUEDE EMPATAR ──────────────────────────────────────────────
--
-- `orden` es una identidad monótona: la asigna una secuencia, avanza SIEMPRE y no se puede repetir
-- ni dentro de la misma transacción. Pasa a ser la autoridad del «cuál fue la última», y
-- `decidido_en` queda para lo que sirve —decirle a una persona cuándo se decidió—.
--
-- `decidido_en` además pasa a `clock_timestamp()`, que sí avanza dentro de una transacción. Sin
-- esto, dos decisiones consecutivas se le muestran al dueño con la misma hora exacta, y eso es
-- mentirle sobre un hecho que la tabla conoce.
--
-- No se toca `decidido_por` ni los permisos: la tabla sigue sin UPDATE ni DELETE.
--
-- ADITIVA: agrega una columna generada por identidad sobre una tabla con 0 filas y cambia dos
-- defaults. No modifica ni borra ningún dato.

alter table public.base_maestra_decision
  add column if not exists orden bigint generated by default as identity;

-- Las filas preexistentes (hoy ninguna) reciben su orden por antigüedad antes de exigir el NOT NULL.
update public.base_maestra_decision d
   set orden = s.n
  from (select id, row_number() over (order by decidido_en, id) n
          from public.base_maestra_decision) s
 where s.id = d.id and d.orden is null;

alter table public.base_maestra_decision
  alter column orden set not null;

alter table public.base_maestra_decision
  drop constraint if exists base_maestra_decision_orden_unico;

alter table public.base_maestra_decision
  add constraint base_maestra_decision_orden_unico unique (orden);

-- `clock_timestamp()` avanza dentro de la transacción; `now()` no.
alter table public.base_maestra_decision
  alter column decidido_en set default clock_timestamp();

-- El índice de reúso pasa a ordenar por `orden`: es el único de los dos que no puede empatar.
drop index if exists public.base_maestra_decision_reuso;
create index base_maestra_decision_reuso
  on public.base_maestra_decision (elemento, unidad, huella, orden desc);

comment on column public.base_maestra_decision.orden is
  'La autoridad del cual fue la ultima. Identidad monotona: avanza siempre y no se repite ni dentro '
  'de la misma transaccion. Existe porque decidido_en tenia default now(), que es la hora de INICIO '
  'DE TRANSACCION: dos decisiones seguidas empataban al microsegundo y order by decidido_en devolvia '
  'cualquiera de las dos — alguien cambiaba de opinion, el sistema decia que si, y seguia cotizando '
  'con la decision vieja. Lo atrapo base-maestra-decision.pg.test.mjs.';

comment on column public.base_maestra_decision.decidido_en is
  'Cuando se decidio, para mostrarselo a una persona. clock_timestamp() y no now(): dentro de una '
  'transaccion now() no avanza y dos decisiones consecutivas se mostraban con la misma hora exacta. '
  'NO es la clave de ordenamiento — esa es orden.';
