// LAS FILAS REALES DE LA PESTAÑA COBRANZAS — Messina (24) y Quattropani (14).
//
// Leídas de `public.cobranzas` el 10/09/2026 a las 18:40, con `es_cobrada()` y el reloj del vencido
// (emisión + 30 días) ya resueltos, que es exactamente lo que publica `public.cliente_cobranza`.
//
// ES UN FIXTURE Y NO UN ESPEJO DEL MUNDO. Lo que los tests afirman sobre él son REGLAS —que los
// grupos sumen las filas, que una anulada no cuente, que el recorte no invente— y no los importes
// del día: si mañana entra una cobranza más, el archivo se regenera y las reglas siguen siendo las
// mismas. Clavar un total del día sería el defecto que ya costó dos veces en este repo (ver
// `test-que-clava-un-derivado-de-dato-vivo`).
//
// LÍMITE DECLARADO: `obra_id` sale del cruce por ORDEN DE COMPRA, que es el primero de los tres
// pasos de `cobranza_imputacion`. Las filas que la base resuelve por alias o por la bolsa del
// cliente aparecen acá con `obra_id: null`, y por eso el grupo «Sin obra atribuida» del fixture es
// más grande que el de la pantalla.

import type { FilaCobranza } from './cobranzasCliente.ts'

export const COBRANZAS_MESSINA: FilaCobranza[] = [
  {
    "cobranza_id": "messina-41",
    "obra_id": "messina-bsa",
    "imputacion": "oc",
    "fila": "41",
    "categoria": "B",
    "fecha_emision": "2024-12-31",
    "factura": null,
    "numero_comprobante": "01-00000227",
    "concepto": "PLANTA DE BSA - 26M3 A FAVOR H-17 - 50%",
    "orden_compra": "00002-00000279",
    "monto_neto": 4073021.7,
    "iva": 855334.56,
    "retenciones": 80221.31,
    "total_bruto": 4848134.95,
    "estado": "Cobrado",
    "esta_cobrada": true,
    "esta_cancelada": false,
    "esta_vencida": false,
    "fecha_cobro": "2026-09-03",
    "forma_cobro": "Echeq"
  },
  {
    "cobranza_id": "messina-89",
    "obra_id": "messina-bsa",
    "imputacion": "oc",
    "fila": "89",
    "categoria": "B",
    "fecha_emision": "2024-12-31",
    "factura": null,
    "numero_comprobante": null,
    "concepto": "PLANTA DE BSA - 50%",
    "orden_compra": "00002-00000279",
    "monto_neto": 4073021.7,
    "iva": 855334.56,
    "retenciones": null,
    "total_bruto": 4928356.26,
    "estado": "Pendiente",
    "esta_cobrada": false,
    "esta_cancelada": false,
    "esta_vencida": true,
    "fecha_cobro": "2026-09-30",
    "forma_cobro": "Transferencia"
  },
  {
    "cobranza_id": "messina-28",
    "obra_id": null,
    "imputacion": null,
    "fila": "28",
    "categoria": "N",
    "fecha_emision": "2026-05-07",
    "factura": null,
    "numero_comprobante": null,
    "concepto": "PILON - Pago parcial (07/05)",
    "orden_compra": null,
    "monto_neto": 2330000,
    "iva": null,
    "retenciones": null,
    "total_bruto": 2330000,
    "estado": "Cobrado",
    "esta_cobrada": true,
    "esta_cancelada": false,
    "esta_vencida": false,
    "fecha_cobro": "2026-05-07",
    "forma_cobro": "Efectivo"
  },
  {
    "cobranza_id": "messina-27",
    "obra_id": "messina-bases-tanque-so2",
    "imputacion": "oc",
    "fila": "27",
    "categoria": "N",
    "fecha_emision": "2026-06-08",
    "factura": null,
    "numero_comprobante": null,
    "concepto": "BASES TANQUE SO2 - Anticipo",
    "orden_compra": "00002-00001864",
    "monto_neto": 6700000,
    "iva": null,
    "retenciones": null,
    "total_bruto": 6700000,
    "estado": "Cobrado",
    "esta_cobrada": true,
    "esta_cancelada": false,
    "esta_vencida": false,
    "fecha_cobro": "2026-05-07",
    "forma_cobro": "Efectivo"
  },
  {
    "cobranza_id": "messina-30",
    "obra_id": null,
    "imputacion": null,
    "fila": "30",
    "categoria": "N",
    "fecha_emision": "2026-06-08",
    "factura": null,
    "numero_comprobante": null,
    "concepto": "PILON",
    "orden_compra": null,
    "monto_neto": 3484558,
    "iva": null,
    "retenciones": null,
    "total_bruto": 3484558,
    "estado": "Cobrado",
    "esta_cobrada": true,
    "esta_cancelada": false,
    "esta_vencida": false,
    "fecha_cobro": "2026-09-10",
    "forma_cobro": "Efectivo"
  },
  {
    "cobranza_id": "messina-34",
    "obra_id": "messina-bases-tanque-so2",
    "imputacion": "oc",
    "fila": "34",
    "categoria": "B",
    "fecha_emision": "2026-06-08",
    "factura": "A",
    "numero_comprobante": "214",
    "concepto": "BASES TANQUE SO2",
    "orden_compra": "00002-00001864",
    "monto_neto": 8375000,
    "iva": 1758750,
    "retenciones": 167500,
    "total_bruto": 9966250,
    "estado": "Cobrado",
    "esta_cobrada": true,
    "esta_cancelada": false,
    "esta_vencida": false,
    "fecha_cobro": "2026-07-29",
    "forma_cobro": "Transferencia"
  },
  {
    "cobranza_id": "messina-38",
    "obra_id": "messina-bases-tanque-so2",
    "imputacion": "oc",
    "fila": "38",
    "categoria": "B",
    "fecha_emision": "2026-06-08",
    "factura": "A",
    "numero_comprobante": "215",
    "concepto": "ADICIONAL - BASE DE TANQUE SO2",
    "orden_compra": "00002-00001923",
    "monto_neto": 5769880,
    "iva": 1211674.8,
    "retenciones": 115397.6,
    "total_bruto": 6866157.2,
    "estado": "Cobrado",
    "esta_cobrada": true,
    "esta_cancelada": false,
    "esta_vencida": false,
    "fecha_cobro": "2026-07-29",
    "forma_cobro": "Transferencia"
  },
  {
    "cobranza_id": "messina-42",
    "obra_id": "messina-bsa",
    "imputacion": "oc",
    "fila": "42",
    "categoria": "B",
    "fecha_emision": "2026-06-18",
    "factura": null,
    "numero_comprobante": "01-00000226",
    "concepto": "ACTUALIZACION DE PRECIOS OC 02-00000279",
    "orden_compra": "00002-00001984",
    "monto_neto": 3583956,
    "iva": 752630.76,
    "retenciones": null,
    "total_bruto": 4336586.76,
    "estado": "Facturado",
    "esta_cobrada": false,
    "esta_cancelada": false,
    "esta_vencida": true,
    "fecha_cobro": "2026-09-17",
    "forma_cobro": "Transferencia"
  },
  {
    "cobranza_id": "messina-43",
    "obra_id": "messina-bsa",
    "imputacion": "oc",
    "fila": "43",
    "categoria": "B",
    "fecha_emision": "2026-06-18",
    "factura": null,
    "numero_comprobante": "01-00000222",
    "concepto": "PLANTA DE BSA - ADICIONAL",
    "orden_compra": "00002-00001985",
    "monto_neto": 5974200,
    "iva": 1254582,
    "retenciones": null,
    "total_bruto": 7228782,
    "estado": "Facturado",
    "esta_cobrada": false,
    "esta_cancelada": false,
    "esta_vencida": true,
    "fecha_cobro": "2026-09-17",
    "forma_cobro": "Transferencia"
  },
  {
    "cobranza_id": "messina-51",
    "obra_id": "messina-pisos-120-rampa",
    "imputacion": "oc",
    "fila": "51",
    "categoria": "B",
    "fecha_emision": "2026-07-20",
    "factura": "FA",
    "numero_comprobante": "01-00000218",
    "concepto": "Pisos 120m2 -  Anticipo 50%",
    "orden_compra": "02-00002097",
    "monto_neto": 3554443.27,
    "iva": 746433.09,
    "retenciones": 66608.87,
    "total_bruto": 4234267.49,
    "estado": "Cobrado",
    "esta_cobrada": true,
    "esta_cancelada": false,
    "esta_vencida": false,
    "fecha_cobro": "2026-08-04",
    "forma_cobro": "Echeq"
  },
  {
    "cobranza_id": "messina-52",
    "obra_id": "messina-pisos-120-rampa",
    "imputacion": "oc",
    "fila": "52",
    "categoria": "B",
    "fecha_emision": "2026-07-20",
    "factura": null,
    "numero_comprobante": "01-00000223",
    "concepto": "Pisos 120m2 - Restante 50%",
    "orden_compra": "02-00002097",
    "monto_neto": 3554443.27,
    "iva": 746433.09,
    "retenciones": 70007.51,
    "total_bruto": 4230868.85,
    "estado": "Cobrado",
    "esta_cobrada": true,
    "esta_cancelada": false,
    "esta_vencida": false,
    "fecha_cobro": "2026-09-03",
    "forma_cobro": "Echeq"
  },
  {
    "cobranza_id": "messina-83",
    "obra_id": "limpieza-de-escombros",
    "imputacion": "oc",
    "fila": "83",
    "categoria": "B",
    "fecha_emision": "2026-08-06",
    "factura": "FA",
    "numero_comprobante": "01-00000225",
    "concepto": "Limpieza de Escombros - Embolsado",
    "orden_compra": "02-00002162",
    "monto_neto": 5008660.65,
    "iva": 1051818.74,
    "retenciones": 98649.44,
    "total_bruto": 5961829.95,
    "estado": "Cobrado",
    "esta_cobrada": true,
    "esta_cancelada": false,
    "esta_vencida": false,
    "fecha_cobro": "2026-09-03",
    "forma_cobro": "Echeq"
  },
  {
    "cobranza_id": "messina-61",
    "obra_id": null,
    "imputacion": null,
    "fila": "61",
    "categoria": "B",
    "fecha_emision": "2026-08-07",
    "factura": null,
    "numero_comprobante": "01-00000224",
    "concepto": "Relevamiento topográfico",
    "orden_compra": "02-00002135",
    "monto_neto": 900000,
    "iva": 189000,
    "retenciones": null,
    "total_bruto": 1089000,
    "estado": "Facturado",
    "esta_cobrada": false,
    "esta_cancelada": false,
    "esta_vencida": true,
    "fecha_cobro": "2026-09-17",
    "forma_cobro": "Transferencia"
  },
  {
    "cobranza_id": "messina-64",
    "obra_id": null,
    "imputacion": null,
    "fila": "64",
    "categoria": "B",
    "fecha_emision": "2026-08-24",
    "factura": "FA",
    "numero_comprobante": "01-00000229",
    "concepto": "Playon Azufre",
    "orden_compra": "Anticipo inicio de obra 50% Blanco $65.000.000 Playon de Azufre. OC 00002-00002173 (11/08/2026) — 50% anticipado / 50% contra entrega",
    "monto_neto": 32500000,
    "iva": 6825000,
    "retenciones": 650000,
    "total_bruto": 38675000,
    "estado": "Cobrado",
    "esta_cobrada": true,
    "esta_cancelada": false,
    "esta_vencida": false,
    "fecha_cobro": "2026-09-08",
    "forma_cobro": "Echeq"
  },
  {
    "cobranza_id": "messina-65",
    "obra_id": null,
    "imputacion": null,
    "fila": "65",
    "categoria": "N",
    "fecha_emision": "2026-08-24",
    "factura": null,
    "numero_comprobante": null,
    "concepto": "Playon Azufre",
    "orden_compra": "Anticipo inicio de obra 50% Negro $37.500.000 Playon de Azufre. Cargar OC",
    "monto_neto": 18159641,
    "iva": null,
    "retenciones": null,
    "total_bruto": 18159641,
    "estado": "Cobrado",
    "esta_cobrada": true,
    "esta_cancelada": false,
    "esta_vencida": false,
    "fecha_cobro": "2026-09-10",
    "forma_cobro": "Efectivo"
  },
  {
    "cobranza_id": "messina-70",
    "obra_id": null,
    "imputacion": null,
    "fila": "70",
    "categoria": "B",
    "fecha_emision": "2026-08-24",
    "factura": null,
    "numero_comprobante": null,
    "concepto": "Playon Azufre - Blanco - Certificación 1/2",
    "orden_compra": "Resto 50% s/ total 65.000.000 — certificación quincenal 1/2 · OC 00002-00002173",
    "monto_neto": 16250000,
    "iva": 3412500,
    "retenciones": null,
    "total_bruto": 19662500,
    "estado": "Pendiente",
    "esta_cobrada": false,
    "esta_cancelada": false,
    "esta_vencida": false,
    "fecha_cobro": "2026-09-22",
    "forma_cobro": "Transferencia"
  },
  {
    "cobranza_id": "messina-71",
    "obra_id": null,
    "imputacion": null,
    "fila": "71",
    "categoria": "B",
    "fecha_emision": "2026-08-24",
    "factura": null,
    "numero_comprobante": null,
    "concepto": "Playon Azufre - Blanco - Certificación 2/2",
    "orden_compra": "Resto 50% s/ total 65.000.000 — certificación quincenal 2/2 · OC 00002-00002173",
    "monto_neto": 16250000,
    "iva": 3412500,
    "retenciones": null,
    "total_bruto": 19662500,
    "estado": "Pendiente",
    "esta_cobrada": false,
    "esta_cancelada": false,
    "esta_vencida": false,
    "fecha_cobro": "2026-10-09",
    "forma_cobro": "Transferencia"
  },
  {
    "cobranza_id": "messina-72",
    "obra_id": null,
    "imputacion": null,
    "fila": "72",
    "categoria": "N",
    "fecha_emision": "2026-08-24",
    "factura": null,
    "numero_comprobante": null,
    "concepto": "Playon Azufre - Negro - Certificación 1/2",
    "orden_compra": "Resto 50% s/ total 37.500.000 — certificación quincenal 1/2",
    "monto_neto": 9400000,
    "iva": null,
    "retenciones": null,
    "total_bruto": 9400000,
    "estado": "Pendiente",
    "esta_cobrada": false,
    "esta_cancelada": false,
    "esta_vencida": false,
    "fecha_cobro": "2026-09-22",
    "forma_cobro": "Efectivo"
  },
  {
    "cobranza_id": "messina-73",
    "obra_id": null,
    "imputacion": null,
    "fila": "73",
    "categoria": "N",
    "fecha_emision": "2026-08-24",
    "factura": null,
    "numero_comprobante": null,
    "concepto": "Playon Azufre - Negro - Certificación 2/2",
    "orden_compra": "Resto 50% s/ total 37.500.000 — certificación quincenal 2/2",
    "monto_neto": 9350000,
    "iva": null,
    "retenciones": null,
    "total_bruto": 9350000,
    "estado": "Pendiente",
    "esta_cobrada": false,
    "esta_cancelada": false,
    "esta_vencida": false,
    "fecha_cobro": "2026-10-09",
    "forma_cobro": "Efectivo"
  },
  {
    "cobranza_id": "messina-92",
    "obra_id": null,
    "imputacion": null,
    "fila": "92",
    "categoria": "B",
    "fecha_emision": "2026-08-24",
    "factura": null,
    "numero_comprobante": null,
    "concepto": "Rampa para Piso 120 m2 — inicio 07/09, 1 semana",
    "orden_compra": "00002-00002226 · cta. cte. 15 días",
    "monto_neto": 2354255.39,
    "iva": 494393.63,
    "retenciones": null,
    "total_bruto": 2848649.02,
    "estado": "Pendiente",
    "esta_cobrada": false,
    "esta_cancelada": false,
    "esta_vencida": false,
    "fecha_cobro": "2026-09-29",
    "forma_cobro": "Transferencia"
  },
  {
    "cobranza_id": "messina-94",
    "obra_id": null,
    "imputacion": null,
    "fila": "94",
    "categoria": "B",
    "fecha_emision": "2026-09-02",
    "factura": null,
    "numero_comprobante": null,
    "concepto": "Adicional tercer muro (armado 20 m) Playon de Azufre — adici",
    "orden_compra": "00002-00002256 · cta. cte. 30 días",
    "monto_neto": 10000000,
    "iva": 2100000,
    "retenciones": null,
    "total_bruto": 12100000,
    "estado": "Pendiente",
    "esta_cobrada": false,
    "esta_cancelada": false,
    "esta_vencida": false,
    "fecha_cobro": "2026-10-28",
    "forma_cobro": "Transferencia"
  },
  {
    "cobranza_id": "messina-95",
    "obra_id": null,
    "imputacion": null,
    "fila": "95",
    "categoria": "B",
    "fecha_emision": "2026-09-03",
    "factura": null,
    "numero_comprobante": null,
    "concepto": "Playón para Dilución de Ácido — Anticipo financiero 50%",
    "orden_compra": "00002-00002266 · cta. cte. 30 días",
    "monto_neto": 10045433.92,
    "iva": 2109541.12,
    "retenciones": null,
    "total_bruto": 12154975.04,
    "estado": "Pendiente",
    "esta_cobrada": false,
    "esta_cancelada": false,
    "esta_vencida": false,
    "fecha_cobro": "2026-10-03",
    "forma_cobro": "Transferencia"
  },
  {
    "cobranza_id": "messina-96",
    "obra_id": null,
    "imputacion": null,
    "fila": "96",
    "categoria": "B",
    "fecha_emision": "2026-09-03",
    "factura": null,
    "numero_comprobante": null,
    "concepto": "Playón para Dilución de Ácido — Saldo 50%, facturable a la f",
    "orden_compra": "00002-00002266 · cta. cte. 30 días",
    "monto_neto": 10045433.92,
    "iva": 2109541.12,
    "retenciones": null,
    "total_bruto": 12154975.04,
    "estado": "Pendiente",
    "esta_cobrada": false,
    "esta_cancelada": false,
    "esta_vencida": false,
    "fecha_cobro": "2026-11-04",
    "forma_cobro": "Transferencia"
  },
  {
    "cobranza_id": "messina-98",
    "obra_id": null,
    "imputacion": null,
    "fila": "98",
    "categoria": "N",
    "fecha_emision": "2026-09-10",
    "factura": null,
    "numero_comprobante": null,
    "concepto": "BASES TANQUE SO2 - Cancelación",
    "orden_compra": null,
    "monto_neto": 2844877,
    "iva": null,
    "retenciones": null,
    "total_bruto": 2844877,
    "estado": "Cobrado",
    "esta_cobrada": true,
    "esta_cancelada": false,
    "esta_vencida": false,
    "fecha_cobro": "2026-09-10",
    "forma_cobro": "Efectivo"
  }
]

export const COBRANZAS_QUATTROPANI: FilaCobranza[] = [
  {
    "cobranza_id": "quattropani-57",
    "obra_id": null,
    "imputacion": null,
    "fila": "57",
    "categoria": "B",
    "fecha_emision": "2026-07-27",
    "factura": "FA",
    "numero_comprobante": "219",
    "concepto": "U$S 11.500 + IVA — 36,5 % del anticipo 50 % + Materiales",
    "orden_compra": "Anticipo 50% inicio obra",
    "monto_neto": 54279685.38,
    "iva": 11398733.93,
    "retenciones": null,
    "total_bruto": 65678419.31,
    "estado": "Cobrado",
    "esta_cobrada": true,
    "esta_cancelada": false,
    "esta_vencida": false,
    "fecha_cobro": "2026-07-28",
    "forma_cobro": "Transferencia"
  },
  {
    "cobranza_id": "quattropani-58",
    "obra_id": null,
    "imputacion": null,
    "fila": "58",
    "categoria": "B",
    "fecha_emision": "2026-07-27",
    "factura": "FA",
    "numero_comprobante": "220",
    "concepto": "U$S 20.000 — 63,5 % del anticipo 50 % · parte U$S 15.400 en ",
    "orden_compra": "Anticipo 50% inicio obra",
    "monto_neto": 23293342.842,
    "iva": null,
    "retenciones": null,
    "total_bruto": 23293342.842,
    "estado": "Cobrado",
    "esta_cobrada": true,
    "esta_cancelada": false,
    "esta_vencida": false,
    "fecha_cobro": "2026-07-31",
    "forma_cobro": "Efectivo"
  },
  {
    "cobranza_id": "quattropani-59",
    "obra_id": null,
    "imputacion": null,
    "fila": "59",
    "categoria": "B",
    "fecha_emision": "2026-07-27",
    "factura": "FA",
    "numero_comprobante": "220",
    "concepto": "U$S 20.000 — 63,5 % del anticipo 50 % · parte U$S 4.600 = $ ",
    "orden_compra": "Anticipo 50% inicio obra",
    "monto_neto": 7130000,
    "iva": null,
    "retenciones": null,
    "total_bruto": 7130000,
    "estado": "Cobrado",
    "esta_cobrada": true,
    "esta_cancelada": false,
    "esta_vencida": false,
    "fecha_cobro": "2026-07-31",
    "forma_cobro": "Efectivo"
  },
  {
    "cobranza_id": "quattropani-60",
    "obra_id": null,
    "imputacion": null,
    "fila": "60",
    "categoria": "B",
    "fecha_emision": "2026-07-28",
    "factura": "FA",
    "numero_comprobante": "220",
    "concepto": "IVA de Factura 220",
    "orden_compra": null,
    "monto_neto": null,
    "iva": 6510000,
    "retenciones": null,
    "total_bruto": 6510000,
    "estado": "Cobrado",
    "esta_cobrada": true,
    "esta_cancelada": false,
    "esta_vencida": false,
    "fecha_cobro": "2026-08-19",
    "forma_cobro": "Transferencia"
  },
  {
    "cobranza_id": "quattropani-74",
    "obra_id": null,
    "imputacion": null,
    "fila": "74",
    "categoria": "B",
    "fecha_emision": "2026-08-18",
    "factura": "FA",
    "numero_comprobante": "230",
    "concepto": "Salón Comercial - Certificación 1/9",
    "orden_compra": "Resto 50% s/ contrato U$S 63.000 + IVA — certificación quincenal 1/9 -  ($1503,6*USD3500)",
    "monto_neto": 5262600,
    "iva": null,
    "retenciones": null,
    "total_bruto": 5262600,
    "estado": "Cobrado",
    "esta_cobrada": true,
    "esta_cancelada": false,
    "esta_vencida": false,
    "fecha_cobro": "2026-09-09",
    "forma_cobro": "Transferencia"
  },
  {
    "cobranza_id": "quattropani-75",
    "obra_id": null,
    "imputacion": null,
    "fila": "75",
    "categoria": "B",
    "fecha_emision": "2026-08-18",
    "factura": null,
    "numero_comprobante": null,
    "concepto": "Salón Comercial - Certificación 2/9",
    "orden_compra": "Resto 50% s/ contrato U$S 63.000 + IVA — certificación quincenal 2/9",
    "monto_neto": 5293941.56,
    "iva": 1111727.73,
    "retenciones": null,
    "total_bruto": 6405669.28,
    "estado": "Pendiente",
    "esta_cobrada": false,
    "esta_cancelada": false,
    "esta_vencida": false,
    "fecha_cobro": "2026-09-25",
    "forma_cobro": "Transferencia"
  },
  {
    "cobranza_id": "quattropani-76",
    "obra_id": null,
    "imputacion": null,
    "fila": "76",
    "categoria": "B",
    "fecha_emision": "2026-08-18",
    "factura": null,
    "numero_comprobante": null,
    "concepto": "Salón Comercial - Certificación 3/9",
    "orden_compra": "Resto 50% s/ contrato U$S 63.000 + IVA — certificación quincenal 3/9",
    "monto_neto": 5293941.56,
    "iva": 1111727.73,
    "retenciones": null,
    "total_bruto": 6405669.28,
    "estado": "Pendiente",
    "esta_cobrada": false,
    "esta_cancelada": false,
    "esta_vencida": false,
    "fecha_cobro": "2026-10-09",
    "forma_cobro": "Transferencia"
  },
  {
    "cobranza_id": "quattropani-77",
    "obra_id": null,
    "imputacion": null,
    "fila": "77",
    "categoria": "B",
    "fecha_emision": "2026-08-18",
    "factura": null,
    "numero_comprobante": null,
    "concepto": "Salón Comercial - Certificación 4/9",
    "orden_compra": "Resto 50% s/ contrato U$S 63.000 + IVA — certificación quincenal 4/9",
    "monto_neto": 5293941.56,
    "iva": 1111727.73,
    "retenciones": null,
    "total_bruto": 6405669.28,
    "estado": "Pendiente",
    "esta_cobrada": false,
    "esta_cancelada": false,
    "esta_vencida": false,
    "fecha_cobro": "2026-10-23",
    "forma_cobro": "Transferencia"
  },
  {
    "cobranza_id": "quattropani-78",
    "obra_id": null,
    "imputacion": null,
    "fila": "78",
    "categoria": "B",
    "fecha_emision": "2026-08-18",
    "factura": null,
    "numero_comprobante": null,
    "concepto": "Salón Comercial - Certificación 5/9",
    "orden_compra": "Resto 50% s/ contrato U$S 63.000 + IVA — certificación quincenal 5/9",
    "monto_neto": 5293941.56,
    "iva": 1111727.73,
    "retenciones": null,
    "total_bruto": 6405669.28,
    "estado": "Pendiente",
    "esta_cobrada": false,
    "esta_cancelada": false,
    "esta_vencida": false,
    "fecha_cobro": "2026-11-06",
    "forma_cobro": "Transferencia"
  },
  {
    "cobranza_id": "quattropani-79",
    "obra_id": null,
    "imputacion": null,
    "fila": "79",
    "categoria": "B",
    "fecha_emision": "2026-08-18",
    "factura": null,
    "numero_comprobante": null,
    "concepto": "Salón Comercial - Certificación 6/9",
    "orden_compra": "Resto 50% s/ contrato U$S 63.000 + IVA — certificación quincenal 6/9",
    "monto_neto": 5293941.56,
    "iva": 1111727.73,
    "retenciones": null,
    "total_bruto": 6405669.28,
    "estado": "Pendiente",
    "esta_cobrada": false,
    "esta_cancelada": false,
    "esta_vencida": false,
    "fecha_cobro": "2026-11-20",
    "forma_cobro": "Transferencia"
  },
  {
    "cobranza_id": "quattropani-80",
    "obra_id": null,
    "imputacion": null,
    "fila": "80",
    "categoria": "B",
    "fecha_emision": "2026-08-18",
    "factura": null,
    "numero_comprobante": null,
    "concepto": "Salón Comercial - Certificación 7/9",
    "orden_compra": "Resto 50% s/ contrato U$S 63.000 + IVA — certificación quincenal 7/9",
    "monto_neto": 5293941.56,
    "iva": 1111727.73,
    "retenciones": null,
    "total_bruto": 6405669.28,
    "estado": "Pendiente",
    "esta_cobrada": false,
    "esta_cancelada": false,
    "esta_vencida": false,
    "fecha_cobro": "2026-12-04",
    "forma_cobro": "Transferencia"
  },
  {
    "cobranza_id": "quattropani-81",
    "obra_id": null,
    "imputacion": null,
    "fila": "81",
    "categoria": "B",
    "fecha_emision": "2026-08-18",
    "factura": null,
    "numero_comprobante": null,
    "concepto": "Salón Comercial - Certificación 8/9",
    "orden_compra": "Resto 50% s/ contrato U$S 63.000 + IVA — certificación quincenal 8/9",
    "monto_neto": 5293941.56,
    "iva": 1111727.73,
    "retenciones": null,
    "total_bruto": 6405669.28,
    "estado": "Pendiente",
    "esta_cobrada": false,
    "esta_cancelada": false,
    "esta_vencida": false,
    "fecha_cobro": "2026-12-18",
    "forma_cobro": "Transferencia"
  },
  {
    "cobranza_id": "quattropani-82",
    "obra_id": null,
    "imputacion": null,
    "fila": "82",
    "categoria": "B",
    "fecha_emision": "2026-08-18",
    "factura": null,
    "numero_comprobante": null,
    "concepto": "Salón Comercial - Certificación 9/9",
    "orden_compra": "Resto 50% s/ contrato U$S 63.000 + IVA — certificación quincenal 9/9",
    "monto_neto": 5293941.56,
    "iva": 1111727.73,
    "retenciones": null,
    "total_bruto": 6405669.28,
    "estado": "Pendiente",
    "esta_cobrada": false,
    "esta_cancelada": false,
    "esta_vencida": false,
    "fecha_cobro": "2026-12-30",
    "forma_cobro": "Transferencia"
  },
  {
    "cobranza_id": "quattropani-97",
    "obra_id": null,
    "imputacion": null,
    "fila": "97",
    "categoria": "B",
    "fecha_emision": "2026-09-10",
    "factura": "FA",
    "numero_comprobante": "230",
    "concepto": "IVA de FC A 0001-00000230 (cert. avance USD 3.500)",
    "orden_compra": null,
    "monto_neto": null,
    "iva": 1105146,
    "retenciones": null,
    "total_bruto": 1105146,
    "estado": "Pendiente",
    "esta_cobrada": false,
    "esta_cancelada": false,
    "esta_vencida": false,
    "fecha_cobro": "2026-09-25",
    "forma_cobro": "Transferencia"
  }
]

